### ISSUE TITLE
running error in "GMPHD_OGM::MinimizedGroupCost"

### ISSUE THREAD

**Issue by rubai1597** [SonginCV/GMPHD-OGM#1]
주어진 코드와 파라미터 값들을 사용하여 MOT17-FRCNN을 테스트 하였을 때, GMPHD_OGM::MinimizeGroupCost 함수의 `this->tracksbyID[groupRects[v].id].pop_back();` 부분에서 vector out of range error가 확인되었습니다. `pop_back()`을 수행하는 과정에서 size가 0이 되면서 오류가 발생한 것 같으니 확인 부탁드립니다.

When i tested "MOT17-FRCNN" sequences with the given code and parameters, the 'vector out of range error' occurs in `this->tracksbyID[groupRects[v].id].pop_back();` in 'GMPHD_OGM::MinimizeGroupCost' function.  It seems to be an error in the process of performing `pop_back()`, as the size became zero.

**Comment by rubai1597** [comment]
I fixed the code which i asked above. Please check.

**Comment by SonginCV** [comment]
안녕하세요. 말씀하신 이슈에 대해 가르쳐 주셔서 감사합니다.
제 PC 상으로는 말씀하신 에러가 발생하지 않는데,

작업을 수행하신 

> "1. OpenCV 버젼, 2. VC 버전, 3. Release 모드 Debug 모드 여부"

""(예, OpenCV3.4.1 x64 VC15 Release)** 와

에러를 발생시키는 
> "Sequence 와 파라미터 값"

 **(예, MOT17-10-FRCNN, 0.9, 20, 1**

을 알려주시면, 동일하게 테스트 해보도록 하겠습니다.

----------------------------------------------------------------------
Hello, thank you for letting me know this issue.
On my PC environments, the issue you mentioned has not occurred.

So, I would tried to detect the issue if you let me know that
your Environments such as 

> "1. OpenCV version, 2. Visual C++ Compiler version, 3. Running Mode (Release or Debug)"

**(e.g., OpenCV3.4.1 x64 VC15 Release)** 

and also which

>  "MOT17 sequence and parameters"

 make the error **(e.g.,  MOT17-10-FRCNN, 0.9, 20, 1).**

**Comment by rubai1597** [comment]
제 작업 환경은 다음과 같습니다.
MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7)

**Comment by rubai1597** [comment]
제 작업환경은 다음과 같습니다.
> MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7)
OpenCV3.4.1
C++17 (boost library의 filesystem 문제로 visual studio에서 C++14에서 C++17로 변경)
boost 1.74.0

visual studio 2019에서 지정해주신 boost library가 build되지 않아서 boost library version을 변경하고 `filesystem`을 사용하기 위해 C++17으로 컴파일 진행하였습니다. Release와 Debug 모두 동일한 에러가 발생했습니다.

이후에 GMPHD_OGM.cpp의 코드 중에서 일부분을 수정해서 제 환경에서 돌아가는 것을 확인했습니다. (변경 사항은 pull request 요청함)

---
My workspace environment as below:
> MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7)
OpenCV3.4.1
C++17 (In my case, there is an error related to filesystem of boost library. Thus, I changed compiler from C++14 to C++17 as setting in visual studio 2019)
boost 1.74.0

The boost library which is specified in README was not built in Visual studio 2019. So i changed boost library version and compile with C++17 to use `filesystem`. I found that error occurs in release and debug mode.

I changed some parts of code in GMPHD_OGM.cpp, and i verified that the changed code can run in my space. (Please, check in pull request.)

**Comment by SonginCV** [comment]
@rubai1597  답변 감사합니다.

에러를 발생시키는 정확한,

> "Sequence 와 파라미터 값"

(예, MOT17-10-FRCNN, 0.9, 20, 1)

도 알려주시면, 동일하게 테스트 해보도록 하겠습니다.

----------------------------------------------------------------------

Please let me know which specific

> "MOT17 sequence and parameters"

make the error (e.g., MOT17-10-FRCNN, 0.9, 20, 1).

**Comment by rubai1597** [comment]
@SonginCV MOT17-02-FRCNN, 0.8, 100, 1 입니다. 감사합니다.

**Comment by SonginCV** [comment]
해당 이슈는

957793c commit 으로 해결되었습니다.

수정전 버젼에서는
아래  `tSize` 의 값이 `pop_back` 전의 값으로 고정되어
아래 for 문 내에서 `pop_back` 을 수행할경우 index out of range 의 문제가 발생하는 것으로 확인 되었습니다.

--------------------------------------------------------------------------------------------------------------------------------
This issue has been solved in 957793c.
Before this commit,
`tSize` was fixed not considering `pop_back`,
so the `vector index out of range` error occurred after `pop back` in for loop as below.

--------------------------------------------------------------------------------------------------------------------------------
https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1357

https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1363

https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1532

https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1535

--------------------------------------------------------------------------------------------------------------------------------
따라서 아래와 같이 `pop_back` 구문을 기존 for 문의 밖으로 두어 따로 처리 하도록 했습니다.

--------------------------------------------------------------------------------------------------------------------------------

Thus, I have taken the `pop_back` lines out of the for loop (`line 1363` and `1535`).

--------------------------------------------------------------------------------------------------------------------------------
https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1380

https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/957793c3427519b4afcb946d8c2620f3925b2fe8/GMPHD-OGM/GMPHD_OGM.cpp#L1552
