### ISSUE TITLE
Error occured when "VISUALIZATION_MAIN_ON"

### ISSUE THREAD

**Issue by hi-one-gg** [SonginCV/GMPHD-OGM#4]
`VISUALIZATION_MAIN_ON` 을 1로 변경후 디버깅없이 실행(Ctrl + F5)할 때에 오픈시피 오류가 납니다.

0으로 했을 시에는 오류가 나지않습니다.

오류 화면 캡쳐합니다. 혹시 짐작가는 해결방법이 있을까요? (demo_....cpp 에서 `seqList`만 제 이미지 경로로변경을하고 `paramsFile`은 변경하지 않긴 했습니다. 이 것이 오류의 원인일 수도 있 을까요? 또한 'qaramsFile`이 가리키는 파일들은 무엇을 의미하나요?)

![image](https://user-images.githubusercontent.com/13531174/116209924-57c1c780-a77d-11eb-8b5b-7248d118ddb4.png)

+추가

에러부분을 찾으려고 디버깅모드(F5)로 해보니 에러가 뜨긴하지만 실행이 되긴하네요... 무슨상황일까요
![image](https://user-images.githubusercontent.com/13531174/116211729-1500ef00-a77f-11eb-8354-d68601e8843b.png)

**Comment by SonginCV** [comment]
1. [Commit version `3e84f4d`](https://github.com/SonginCV/GMPHD-OGM_Tracker/commit/3e84f4d0a4fc7cb42981b2eb80c6670eba562e6d)
가르쳐 주신 덕분에 해당 에러는 고쳐서 커밋했습니다.
Visualization 할 때 ID 글씨 너비에 회색배경의 너비도 맞추려는 구문이었는데, 
ID 가 0일때도 log연산을 하게 되어있었네요.

2. [MOT17train_FRCNN.txt](https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/master/GMPHD-OGM/params/MOT17train_FRCNN.txt)
을 기준으로 parameter 에 대해 설명드리면
MOT17-02-FRCNN, 0.8, 100, 1 의 경우 차례대로
-씬이름
-Score 0.8 이상의 detection 만 tracking input 으로 사용, 
-Track-to-Track association 을 하는 최대 interval (live track 의 생성시점 - lost track 의 마지막 시점): 즉 tracking 실패한지 100 프레임을 초과한 것은 다시 살리는 대상이 안된다는 의미 입니다.
-Track init 이 되는 연속 성공횟수 기준  (프레임수) : 1 이므로 latency (delay 없이 바로 생성)
의 의미를 지닙니다.

3. 추가적으로 제가 공개한것은 MOT15 와 MOT17 training set 에 대한 파라미터들 뿐이라, 
MOT20 데이터에 대한 실험이나 직관을 통해 적합한 파라미터를 찾아내시면 성능향상에 도움이 되실것 같습니다.

**Comment by hi-one-gg** [comment]
> 1. [Commit version `3e84f4d`](https://github.com/SonginCV/GMPHD-OGM_Tracker/commit/3e84f4d0a4fc7cb42981b2eb80c6670eba562e6d)
>    가르쳐 주신 덕분에 해당 에러는 고쳐서 커밋했습니다.
>    Visualization 할 때 ID 글씨 너비에 회색배경의 너비도 맞추려는 구문이었는데,
>    ID 가 0일때도 log연산을 하게 되어있었네요.
> 2. [MOT17train_FRCNN.txt](https://github.com/SonginCV/GMPHD-OGM_Tracker/blob/master/GMPHD-OGM/params/MOT17train_FRCNN.txt)
>    을 기준으로 parameter 에 대해 설명드리면
>    MOT17-02-FRCNN, 0.8, 100, 1 의 경우 차례대로
>    -씬이름
>    -Score 0.8 이상의 detection 만 tracking input 으로 사용,
>    -Track-to-Track association 을 하는 최대 interval (live track 의 생성시점 - lost track 의 마지막 시점): 즉 tracking 실패한지 100 프레임을 초과한 것은 다시 살리는 대상이 안된다는 의미 입니다.
>    -Track init 이 되는 연속 성공횟수 기준  (프레임수) : 1 이므로 latency (delay 없이 바로 생성)
>    의 의미를 지닙니다.
> 3. 추가적으로 제가 공개한것은 MOT15 와 MOT17 training set 에 대한 파라미터들 뿐이라,
>    MOT20 데이터에 대한 실험이나 직관을 통해 적합한 파라미터를 찾아내시면 성능향상에 도움이 되실것 같습니다.

감사합니다 파라미터도 잘 이해가 됐고 동작도 잘 되네요 ^^
그런데 하나 더 여쭤보고싶은게 있습니다. 현 레포의 gif에 나와있는 것 처럼 빠른 fps를 기대 했는데 실제 돌려보니 처음엔 20-30fps가 나오다가 한 100프레임?정도 지났을 무렵부턴 아래 사진과 같이 fps가 확 떨어져 버립니다.
파라미터 문제일까 싶어서 det_conf를 0.99로 설정을 해서 최대한 추적객체를 줄여봐도 똑같습니다. 혹시 제 컴퓨터가 HDD를 사용하고 있는데 opencv에서 이미지를 불러오는 과정가운데 속도가 느려서 일어나는 문제일까요..? 이미지셋의 해상도는 기본값인 1080p이며 이름은 ```MOT20-01``` 입니다. 캡쳐화면 첨부합니다.
![image](https://user-images.githubusercontent.com/13531174/116833849-6e8d7180-abf6-11eb-8d83-2d5058eebcc5.png)

+추가) 파라미터를 바꿔보니 14~20fps정도가 나오긴하네요 그러나 현 레포의 gif처럼 어메이징한 속도는 나오지 않네요 혹시 제가 실수하고 있는 부분이 있을까요 ^^?

**Comment by SonginCV** [comment]
안녕하세요.

그동안 다른 논문 작성 및 관련 코드 정리를 하느라 이제 답변을 드립니다.

MOT20 에서 속도가 느려지는 원인이
MOT15 나 MOT17 대비 객체수가 월등하게 많아 느려지는것으로 여기고 있었는데

함수 및 코드 구문별 속도 측정 결과 많아진 객체수를 감안해도 과도하게 느려져서
해당 원인을 발견해서 수정 후 새로 commit 했습니다.

기존 코드에서는
`DataAssocTrkWise` 함수 내의 for x for 구문에서
`map<int, vector<BBTrk>>` 에 매번 접근하여
누적되는 track 수가 많아질수록 속도가 저하되고 있었네요.

해당 구문을 미리 `vector<BBTrk>` 나 `BBTrk` 에 복사해두고 컨테이너에 접근하는 횟수를 줄이니
MOT17 에서는 두배가량 속도가 빨라지고 MOT20 에서도 50 FPS 이상으로 빠르게 돌아가는것을 확인했습니다.

상세한 변경 내역을 보시려면 아래링크를 참고해주세요.
 [Comparison of `3e84f4d` and `47cfaca3`](https://github.com/SonginCV/GMPHD-OGM_Tracker/commit/47cfaca3a91c652c2863b098b01441f3d85fdc46?branch=47cfaca3a91c652c2863b098b01441f3d85fdc46&diff=split)

※ TIP1. MOT20 에서 제공되는 Public Detection 결과는 언제부터인지 모르겠지만 score 가 0 또는 1 수준으로 극단적이니 
다른 Detector를 사용하시는게 scene 별로 적절한 det_conf 값을 찾아주는데 편리하실거에요.

※ TIP2. 추가적으로 Visualization 자체가 프레임당 0.02 초 정도는 소요가 되니
이미지의 사이즈를 줄여서 출력하시는게 실시간으로 빠르게 돌아가는 것을 확인하실 수 있을거에요.
콘솔에 출력되는 속도 Visualization 을 제외하고 MOT process 에 대해서만 측정이 됩니다.

**Comment by hi-one-gg** [comment]
> 안녕하세요.
> 
> 그동안 다른 논문 작성 및 관련 코드 정리를 하느라 이제 답변을 드립니다.
> 
> MOT20 에서 속도가 느려지는 원인이
> MOT15 나 MOT17 대비 객체수가 월등하게 많아 느려지는것으로 여기고 있었는데
> 
> 함수 및 코드 구문별 속도 측정 결과 많아진 객체수를 감안해도 과도하게 느려져서
> 해당 원인을 발견해서 수정 후 새로 commit 했습니다.
> 
> 기존 코드에서는
> `DataAssocTrkWise` 함수 내의 for x for 구문에서
> `map<int, vector<BBTrk>>` 에 매번 접근하여
> 누적되는 track 수가 많아질수록 속도가 저하되고 있었네요.
> 
> 해당 구문을 미리 `vector<BBTrk>` 나 `BBTrk` 에 복사해두고 컨테이너에 접근하는 횟수를 줄이니
> MOT17 에서는 두배가량 속도가 빨라지고 MOT20 에서도 50 FPS 이상으로 빠르게 돌아가는것을 확인했습니다.
> 
> 상세한 변경 내역을 보시려면 아래링크를 참고해주세요.
> [Comparison of `3e84f4d` and `47cfaca3`](https://github.com/SonginCV/GMPHD-OGM_Tracker/commit/47cfaca3a91c652c2863b098b01441f3d85fdc46?branch=47cfaca3a91c652c2863b098b01441f3d85fdc46&diff=split)
> 
> ※ TIP1. MOT20 에서 제공되는 Public Detection 결과는 언제부터인지 모르겠지만 score 가 0 또는 1 수준으로 극단적이니
> 다른 Detector를 사용하시는게 scene 별로 적절한 det_conf 값을 찾아주는데 편리하실거에요.
> 
> ※ TIP2. 추가적으로 Visualization 자체가 프레임당 0.02 초 정도는 소요가 되니
> 이미지의 사이즈를 줄여서 출력하시는게 실시간으로 빠르게 돌아가는 것을 확인하실 수 있을거에요.
> 콘솔에 출력되는 속도 Visualization 을 제외하고 MOT process 에 대해서만 측정이 됩니다.

와... 기대됩니다. 최근엔 Deepsort를 사용해보고있는데 다시 써봐야겠습니다. 혹시 이 레포의 코드들을 GPU로 연산하려는 계획도 있으신가요? 이젠에 보니 CPU로만 돌아가는 것 같아서요 

무튼.. 개선해주셔서 감사합니다 후기남기겠습니바

**Comment by SonginCV** [comment]
CPU의 multi-processing 만을 이용해서 다중클래스-다중객체 추적을 구현하는 목적으로 개발된것이라,
GPU가 필요할만큼 많은 연산량이 필요하진 않습니다. 

또한, 내부적으로도 복잡한 appearance feature 를 이용하지 않고 
detection bounding box 의 center point 만 이용하여 GMPHD filtering 기반으로 추적이 진행되는데
이부분을 GPU로 연산하는 코드로 바꿀경우 
CPU 와 GPU 간에 데이터를 옮겼다 가져오는 부분에서 오히려 bottleneck 이 발생해서
속도개선에 크게 도움이 될것 같지는 않습니다. :)
